spring.sql.init.mode=always
spring.application.name=ClickMenu
spring.datasource.url=jdbc:h2:mem:restaurante;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver

api.security.token.secret=${JWT_SECRET:my-secret-key}

#spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
